#############################################################################
#                                                                           #
# File: appveyor.yml                                                        #
# Project: HireSphere                                                       #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################
image: Visual Studio 2022

branches:
  except:
    - gh-pages

build: off

clone_script:
  - cmd: |
      git config --global core.autocrlf true
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%

before_test:
  - cmd: npm install

test_script:
  - ps: npm run cypress:run

after_test:
  - ps: |
      $client = New-Object System.Net.WebClient
      $client.UploadFile("https://ci.appveyor.com/api/testresults/junit/$Env:APPVEYOR_JOB_ID", (Resolve-Path ".\artifacts\cypress\test-results.xml"))     
